ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [ com.directory.ApplicationKt.module ]
  }
}

database {
  url = ${?DATABASE_URL}
  url = "jdbc:postgresql://ep-misty-block-apwh1ut8-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

  user = ${?DATABASE_USER}
  user = "neondb_owner"

  password = ${?DATABASE_PASSWORD}
  password = "npg_9WlE2pFXHfrM"
}